// <auto-generated />
using System;
using Erp.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Erp.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ErpDbContext))]
    [Migration("20260823171909_AddUserCredentials")]
    partial class AddUserCredentials
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("erp")
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Erp.Domain.Accounting.Account", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("AccountType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid>("ChartOfAccountsId")
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsPosting")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<Guid?>("ParentAccountId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ParentAccountId");

                    b.HasIndex("ChartOfAccountsId", "Code")
                        .IsUnique();

                    b.ToTable("accounts", "erp");
                });

            modelBuilder.Entity("Erp.Domain.Accounting.AccountingPeriod", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId", "Name")
                        .IsUnique();

                    b.ToTable("accounting_periods", "erp");
                });

            modelBuilder.Entity("Erp.Domain.Accounting.AccountingTransaction", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateOnly>("TransactionDate")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.ToTable("accounting_transactions", "erp");
                });

            modelBuilder.Entity("Erp.Domain.Accounting.CashBankAccount", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("AccountType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<Guid>("PostingAccountId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("PostingAccountId");

                    b.HasIndex("CompanyId", "Name")
                        .IsUnique();

                    b.HasIndex("CompanyId", "PostingAccountId")
                        .IsUnique();

                    b.ToTable("cash_bank_accounts", "erp");
                });

            modelBuilder.Entity("Erp.Domain.Accounting.ChartOfAccounts", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId")
                        .IsUnique();

                    b.ToTable("charts_of_accounts", "erp");
                });

            modelBuilder.Entity("Erp.Domain.Accounting.GeneralLedgerEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("AccountingPeriodId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("JournalEntryId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("JournalEntryLineId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("PostedDate")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.HasIndex("AccountingPeriodId");

                    b.HasIndex("JournalEntryId");

                    b.HasIndex("JournalEntryLineId")
                        .IsUnique();

                    b.HasIndex("CompanyId", "AccountId", "AccountingPeriodId", "PostedDate");

                    b.ToTable("general_ledger_entries", "erp");
                });

            modelBuilder.Entity("Erp.Domain.Accounting.JournalEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("AccountingPeriodId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("AccountingTransactionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid");

                    b.Property<string>("CurrencyCode")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character(3)")
                        .IsFixedLength();

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("DocumentNumber")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("document_number");

                    b.Property<DateOnly>("EntryDate")
                        .HasColumnType("date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("AccountingPeriodId");

                    b.HasIndex("AccountingTransactionId");

                    b.HasIndex("CompanyId", "AccountingPeriodId", "EntryDate");

                    b.ToTable("journal_entries", "erp");
                });

            modelBuilder.Entity("Erp.Domain.Accounting.JournalEntryLine", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("BusinessPartnerId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("JournalEntryId")
                        .HasColumnType("uuid");

                    b.Property<int>("LineNumber")
                        .HasColumnType("integer");

                    b.Property<Guid?>("OpenItemId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.HasIndex("BusinessPartnerId");

                    b.HasIndex("OpenItemId");

                    b.HasIndex("JournalEntryId", "LineNumber")
                        .IsUnique();

                    b.ToTable("journal_entry_lines", "erp");
                });

            modelBuilder.Entity("Erp.Domain.Accounting.OpenItem", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("BusinessPartnerId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid");

                    b.Property<string>("DocumentNumber")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("document_number");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("BusinessPartnerId");

                    b.HasIndex("CompanyId", "BusinessPartnerId", "Type");

                    b.ToTable("open_items", "erp");
                });

            modelBuilder.Entity("Erp.Domain.Accounting.PostingProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId", "Name")
                        .IsUnique();

                    b.ToTable("posting_profiles", "erp");
                });

            modelBuilder.Entity("Erp.Domain.Accounting.PostingProfileEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid");

                    b.Property<string>("PostingKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("PostingProfileId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.HasIndex("PostingProfileId", "PostingKey")
                        .IsUnique();

                    b.ToTable("posting_profile_entries", "erp");
                });

            modelBuilder.Entity("Erp.Domain.Identity.Permission", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.ToTable("permissions", "erp");
                });

            modelBuilder.Entity("Erp.Domain.Identity.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId", "Name")
                        .IsUnique();

                    b.ToTable("roles", "erp");
                });

            modelBuilder.Entity("Erp.Domain.Identity.RolePermission", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PermissionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("PermissionId");

                    b.HasIndex("RoleId", "PermissionId")
                        .IsUnique();

                    b.ToTable("role_permissions", "erp");
                });

            modelBuilder.Entity("Erp.Domain.Identity.User", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("users", "erp");
                });

            modelBuilder.Entity("Erp.Domain.Identity.UserRoleAssignment", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.HasIndex("RoleId");

                    b.HasIndex("UserId", "CompanyId", "RoleId")
                        .IsUnique();

                    b.ToTable("user_role_assignments", "erp");
                });

            modelBuilder.Entity("Erp.Domain.Inventory.InventoryBalance", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("WarehouseId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("WarehouseId");

                    b.HasIndex("CompanyId", "ProductId", "WarehouseId")
                        .IsUnique();

                    b.ToTable("inventory_balances", "erp");
                });

            modelBuilder.Entity("Erp.Domain.Inventory.InventoryTransaction", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid");

                    b.Property<string>("MovementType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("WarehouseId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("WarehouseId");

                    b.HasIndex("CompanyId", "ProductId", "WarehouseId", "OccurredAt");

                    b.ToTable("inventory_transactions", "erp");
                });

            modelBuilder.Entity("Erp.Domain.Inventory.Warehouse", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId", "Code")
                        .IsUnique();

                    b.ToTable("warehouses", "erp");
                });

            modelBuilder.Entity("Erp.Domain.MasterData.BusinessPartner", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("LegalName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("PaymentTermsDays")
                        .HasColumnType("integer");

                    b.Property<string>("TaxIdentifier")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId", "Code")
                        .IsUnique();

                    b.ToTable("business_partners", "erp");
                });

            modelBuilder.Entity("Erp.Domain.MasterData.Currency", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character(3)")
                        .IsFixedLength();

                    b.Property<int>("DecimalPlaces")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("currencies", "erp");
                });

            modelBuilder.Entity("Erp.Domain.MasterData.CustomerProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("BusinessPartnerId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ReceivableAccountId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("BusinessPartnerId")
                        .IsUnique();

                    b.HasIndex("ReceivableAccountId");

                    b.ToTable("customer_profiles", "erp");
                });

            modelBuilder.Entity("Erp.Domain.MasterData.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid?>("PostingProfileId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ProductCategoryId")
                        .HasColumnType("uuid");

                    b.Property<string>("ProductType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Sku")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<Guid>("StockUnitOfMeasureId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("PostingProfileId");

                    b.HasIndex("ProductCategoryId");

                    b.HasIndex("StockUnitOfMeasureId");

                    b.HasIndex("CompanyId", "Sku")
                        .IsUnique();

                    b.ToTable("products", "erp");
                });

            modelBuilder.Entity("Erp.Domain.MasterData.ProductCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<Guid?>("ParentCategoryId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ParentCategoryId");

                    b.HasIndex("CompanyId", "Code")
                        .IsUnique();

                    b.ToTable("product_categories", "erp");
                });

            modelBuilder.Entity("Erp.Domain.MasterData.SupplierProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("BusinessPartnerId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("PayableAccountId")
                        .HasColumnType("uuid");

                    b.Property<string>("SupplierReference")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("BusinessPartnerId")
                        .IsUnique();

                    b.HasIndex("PayableAccountId");

                    b.ToTable("supplier_profiles", "erp");
                });

            modelBuilder.Entity("Erp.Domain.MasterData.TaxCode", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("EffectiveFrom")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("EffectiveTo")
                        .HasColumnType("date");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsRecoverable")
                        .HasColumnType("boolean");

                    b.Property<decimal>("Rate")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId", "Code")
                        .IsUnique();

                    b.ToTable("tax_codes", "erp");
                });

            modelBuilder.Entity("Erp.Domain.MasterData.UnitOfMeasure", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid?>("CompanyId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("ConversionFactorToBase")
                        .HasPrecision(19, 6)
                        .HasColumnType("numeric(19,6)");

                    b.Property<int>("DecimalPlaces")
                        .HasColumnType("integer");

                    b.Property<string>("Dimension")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId", "Code")
                        .IsUnique();

                    b.ToTable("units_of_measure", "erp");
                });

            modelBuilder.Entity("Erp.Domain.Organizations.Company", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("BaseCurrencyCode")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character(3)")
                        .IsFixedLength();

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<string>("TaxIdentifier")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId", "Code")
                        .IsUnique();

                    b.ToTable("companies", "erp");
                });

            modelBuilder.Entity("Erp.Domain.Organizations.Organization", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("organizations", "erp");
                });

            modelBuilder.Entity("Erp.Domain.Payments.Payment", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("BusinessPartnerId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CashBankAccountId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid");

                    b.Property<string>("Direction")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("ExternalReference")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateOnly>("PaymentDate")
                        .HasColumnType("date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("BusinessPartnerId");

                    b.HasIndex("CashBankAccountId");

                    b.HasIndex("CompanyId", "BusinessPartnerId", "PaymentDate");

                    b.ToTable("payments", "erp");
                });

            modelBuilder.Entity("Erp.Domain.Payments.PaymentAllocation", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("OpenItemId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PaymentId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("OpenItemId");

                    b.HasIndex("PaymentId", "OpenItemId")
                        .IsUnique();

                    b.ToTable("payment_allocations", "erp");
                });

            modelBuilder.Entity("Erp.Domain.Purchasing.PurchaseInvoice", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid");

                    b.Property<string>("CurrencyCode")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character(3)")
                        .IsFixedLength();

                    b.Property<string>("DocumentNumber")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("document_number");

                    b.Property<DateOnly?>("DueDate")
                        .HasColumnType("date");

                    b.Property<DateOnly>("InvoiceDate")
                        .HasColumnType("date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid>("SupplierId")
                        .HasColumnType("uuid");

                    b.Property<string>("SupplierReference")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("SupplierId");

                    b.HasIndex("CompanyId", "DocumentNumber")
                        .IsUnique();

                    b.HasIndex("CompanyId", "SupplierId", "InvoiceDate");

                    b.ToTable("purchase_invoices", "erp");
                });

            modelBuilder.Entity("Erp.Domain.Purchasing.PurchaseInvoiceLine", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("LineNumber")
                        .HasColumnType("integer");

                    b.Property<Guid?>("PostingProfileId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PurchaseInvoiceId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("PostingProfileId");

                    b.HasIndex("ProductId");

                    b.HasIndex("PurchaseInvoiceId", "LineNumber")
                        .IsUnique();

                    b.ToTable("purchase_invoice_lines", "erp");
                });

            modelBuilder.Entity("Erp.Domain.Sales.SalesInvoice", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid");

                    b.Property<string>("CurrencyCode")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character(3)")
                        .IsFixedLength();

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid");

                    b.Property<string>("DocumentNumber")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("document_number");

                    b.Property<DateOnly?>("DueDate")
                        .HasColumnType("date");

                    b.Property<DateOnly>("InvoiceDate")
                        .HasColumnType("date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("CompanyId", "DocumentNumber")
                        .IsUnique();

                    b.HasIndex("CompanyId", "CustomerId", "InvoiceDate");

                    b.ToTable("sales_invoices", "erp");
                });

            modelBuilder.Entity("Erp.Domain.Sales.SalesInvoiceLine", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<decimal>("DiscountPercentage")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.Property<int>("LineNumber")
                        .HasColumnType("integer");

                    b.Property<Guid?>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SalesInvoiceId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("SalesInvoiceId", "LineNumber")
                        .IsUnique();

                    b.ToTable("sales_invoice_lines", "erp");
                });

            modelBuilder.Entity("Erp.Infrastructure.Authentication.UserCredential", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("PasswordChangedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("user_credentials", "erp");
                });

            modelBuilder.Entity("Erp.Domain.Accounting.Account", b =>
                {
                    b.HasOne("Erp.Domain.Accounting.ChartOfAccounts", null)
                        .WithMany("Accounts")
                        .HasForeignKey("ChartOfAccountsId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Erp.Domain.Accounting.Account", null)
                        .WithMany()
                        .HasForeignKey("ParentAccountId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Erp.Domain.Accounting.AccountingPeriod", b =>
                {
                    b.HasOne("Erp.Domain.Organizations.Company", null)
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsOne("Erp.Domain.Common.DateRange", "DateRange", b1 =>
                        {
                            b1.Property<Guid>("AccountingPeriodId")
                                .HasColumnType("uuid");

                            b1.Property<DateOnly>("EndDate")
                                .HasColumnType("date")
                                .HasColumnName("end_date");

                            b1.Property<DateOnly>("StartDate")
                                .HasColumnType("date")
                                .HasColumnName("start_date");

                            b1.HasKey("AccountingPeriodId");

                            b1.ToTable("accounting_periods", "erp");

                            b1.WithOwner()
                                .HasForeignKey("AccountingPeriodId");
                        });

                    b.Navigation("DateRange")
                        .IsRequired();
                });

            modelBuilder.Entity("Erp.Domain.Accounting.AccountingTransaction", b =>
                {
                    b.HasOne("Erp.Domain.Organizations.Company", null)
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsOne("Erp.Domain.Common.SourceReference", "SourceReference", b1 =>
                        {
                            b1.Property<Guid>("AccountingTransactionId")
                                .HasColumnType("uuid");

                            b1.Property<Guid>("AggregateId")
                                .HasColumnType("uuid")
                                .HasColumnName("source_aggregate_id");

                            b1.Property<string>("EventType")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("source_event_type");

                            b1.Property<string>("Module")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("source_module");

                            b1.HasKey("AccountingTransactionId");

                            b1.HasIndex("Module", "AggregateId", "EventType")
                                .IsUnique();

                            b1.ToTable("accounting_transactions", "erp");

                            b1.WithOwner()
                                .HasForeignKey("AccountingTransactionId");
                        });

                    b.Navigation("SourceReference")
                        .IsRequired();
                });

            modelBuilder.Entity("Erp.Domain.Accounting.CashBankAccount", b =>
                {
                    b.HasOne("Erp.Domain.Organizations.Company", null)
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Erp.Domain.Accounting.Account", null)
                        .WithMany()
                        .HasForeignKey("PostingAccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Erp.Domain.Accounting.ChartOfAccounts", b =>
                {
                    b.HasOne("Erp.Domain.Organizations.Company", null)
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Erp.Domain.Accounting.GeneralLedgerEntry", b =>
                {
                    b.HasOne("Erp.Domain.Accounting.Account", null)
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Erp.Domain.Accounting.AccountingPeriod", null)
                        .WithMany()
                        .HasForeignKey("AccountingPeriodId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Erp.Domain.Organizations.Company", null)
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Erp.Domain.Accounting.JournalEntry", null)
                        .WithMany()
                        .HasForeignKey("JournalEntryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Erp.Domain.Accounting.JournalEntryLine", null)
                        .WithMany()
                        .HasForeignKey("JournalEntryLineId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsOne("Erp.Domain.Common.Money", "Credit", b1 =>
                        {
                            b1.Property<Guid>("GeneralLedgerEntryId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("Amount")
                                .HasPrecision(19, 4)
                                .HasColumnType("numeric(19,4)")
                                .HasColumnName("credit_amount");

                            b1.Property<string>("CurrencyCode")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("character(3)")
                                .HasColumnName("credit_currency_code")
                                .IsFixedLength();

                            b1.HasKey("GeneralLedgerEntryId");

                            b1.ToTable("general_ledger_entries", "erp");

                            b1.WithOwner()
                                .HasForeignKey("GeneralLedgerEntryId");
                        });

                    b.OwnsOne("Erp.Domain.Common.Money", "Debit", b1 =>
                        {
                            b1.Property<Guid>("GeneralLedgerEntryId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("Amount")
                                .HasPrecision(19, 4)
                                .HasColumnType("numeric(19,4)")
                                .HasColumnName("debit_amount");

                            b1.Property<string>("CurrencyCode")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("character(3)")
                                .HasColumnName("debit_currency_code")
                                .IsFixedLength();

                            b1.HasKey("GeneralLedgerEntryId");

                            b1.ToTable("general_ledger_entries", "erp");

                            b1.WithOwner()
                                .HasForeignKey("GeneralLedgerEntryId");
                        });

                    b.Navigation("Credit")
                        .IsRequired();

                    b.Navigation("Debit")
                        .IsRequired();
                });

            modelBuilder.Entity("Erp.Domain.Accounting.JournalEntry", b =>
                {
                    b.HasOne("Erp.Domain.Accounting.AccountingPeriod", null)
                        .WithMany()
                        .HasForeignKey("AccountingPeriodId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Erp.Domain.Accounting.AccountingTransaction", null)
                        .WithMany()
                        .HasForeignKey("AccountingTransactionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Erp.Domain.Organizations.Company", null)
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Erp.Domain.Accounting.JournalEntryLine", b =>
                {
                    b.HasOne("Erp.Domain.Accounting.Account", null)
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Erp.Domain.MasterData.BusinessPartner", null)
                        .WithMany()
                        .HasForeignKey("BusinessPartnerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Erp.Domain.Accounting.JournalEntry", null)
                        .WithMany("Lines")
                        .HasForeignKey("JournalEntryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Erp.Domain.Accounting.OpenItem", null)
                        .WithMany()
                        .HasForeignKey("OpenItemId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.OwnsOne("Erp.Domain.Common.Money", "Credit", b1 =>
                        {
                            b1.Property<Guid>("JournalEntryLineId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("Amount")
                                .HasPrecision(19, 4)
                                .HasColumnType("numeric(19,4)")
                                .HasColumnName("credit_amount");

                            b1.Property<string>("CurrencyCode")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("character(3)")
                                .HasColumnName("credit_currency_code")
                                .IsFixedLength();

                            b1.HasKey("JournalEntryLineId");

                            b1.ToTable("journal_entry_lines", "erp");

                            b1.WithOwner()
                                .HasForeignKey("JournalEntryLineId");
                        });

                    b.OwnsOne("Erp.Domain.Common.Money", "Debit", b1 =>
                        {
                            b1.Property<Guid>("JournalEntryLineId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("Amount")
                                .HasPrecision(19, 4)
                                .HasColumnType("numeric(19,4)")
                                .HasColumnName("debit_amount");

                            b1.Property<string>("CurrencyCode")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("character(3)")
                                .HasColumnName("debit_currency_code")
                                .IsFixedLength();

                            b1.HasKey("JournalEntryLineId");

                            b1.ToTable("journal_entry_lines", "erp");

                            b1.WithOwner()
                                .HasForeignKey("JournalEntryLineId");
                        });

                    b.Navigation("Credit")
                        .IsRequired();

                    b.Navigation("Debit")
                        .IsRequired();
                });

            modelBuilder.Entity("Erp.Domain.Accounting.OpenItem", b =>
                {
                    b.HasOne("Erp.Domain.MasterData.BusinessPartner", null)
                        .WithMany()
                        .HasForeignKey("BusinessPartnerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Erp.Domain.Organizations.Company", null)
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsOne("Erp.Domain.Common.Money", "OriginalAmount", b1 =>
                        {
                            b1.Property<Guid>("OpenItemId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("Amount")
                                .HasPrecision(19, 4)
                                .HasColumnType("numeric(19,4)")
                                .HasColumnName("original_amount");

                            b1.Property<string>("CurrencyCode")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("character(3)")
                                .HasColumnName("original_currency_code")
                                .IsFixedLength();

                            b1.HasKey("OpenItemId");

                            b1.ToTable("open_items", "erp");

                            b1.WithOwner()
                                .HasForeignKey("OpenItemId");
                        });

                    b.OwnsOne("Erp.Domain.Common.Money", "SettledAmount", b1 =>
                        {
                            b1.Property<Guid>("OpenItemId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("Amount")
                                .HasPrecision(19, 4)
                                .HasColumnType("numeric(19,4)")
                                .HasColumnName("settled_amount");

                            b1.Property<string>("CurrencyCode")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("character(3)")
                                .HasColumnName("settled_currency_code")
                                .IsFixedLength();

                            b1.HasKey("OpenItemId");

                            b1.ToTable("open_items", "erp");

                            b1.WithOwner()
                                .HasForeignKey("OpenItemId");
                        });

                    b.OwnsOne("Erp.Domain.Common.SourceReference", "SourceReference", b1 =>
                        {
                            b1.Property<Guid>("OpenItemId")
                                .HasColumnType("uuid");

                            b1.Property<Guid>("AggregateId")
                                .HasColumnType("uuid")
                                .HasColumnName("source_aggregate_id");

                            b1.Property<string>("EventType")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("source_event_type");

                            b1.Property<string>("Module")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("source_module");

                            b1.HasKey("OpenItemId");

                            b1.HasIndex("Module", "AggregateId", "EventType")
                                .IsUnique();

                            b1.ToTable("open_items", "erp");

                            b1.WithOwner()
                                .HasForeignKey("OpenItemId");
                        });

                    b.Navigation("OriginalAmount")
                        .IsRequired();

                    b.Navigation("SettledAmount")
                        .IsRequired();

                    b.Navigation("SourceReference")
                        .IsRequired();
                });

            modelBuilder.Entity("Erp.Domain.Accounting.PostingProfile", b =>
                {
                    b.HasOne("Erp.Domain.Organizations.Company", null)
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Erp.Domain.Accounting.PostingProfileEntry", b =>
                {
                    b.HasOne("Erp.Domain.Accounting.Account", null)
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Erp.Domain.Accounting.PostingProfile", null)
                        .WithMany("Entries")
                        .HasForeignKey("PostingProfileId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Erp.Domain.Identity.Role", b =>
                {
                    b.HasOne("Erp.Domain.Organizations.Company", null)
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Erp.Domain.Identity.RolePermission", b =>
                {
                    b.HasOne("Erp.Domain.Identity.Permission", null)
                        .WithMany()
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Erp.Domain.Identity.Role", null)
                        .WithMany("Permissions")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Erp.Domain.Identity.UserRoleAssignment", b =>
                {
                    b.HasOne("Erp.Domain.Organizations.Company", null)
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Erp.Domain.Identity.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Erp.Domain.Identity.User", null)
                        .WithMany("RoleAssignments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Erp.Domain.Inventory.InventoryBalance", b =>
                {
                    b.HasOne("Erp.Domain.Organizations.Company", null)
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Erp.Domain.MasterData.Product", null)
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Erp.Domain.Inventory.Warehouse", null)
                        .WithMany()
                        .HasForeignKey("WarehouseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsOne("Erp.Domain.Common.Money", "InventoryValue", b1 =>
                        {
                            b1.Property<Guid>("InventoryBalanceId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("Amount")
                                .HasPrecision(19, 4)
                                .HasColumnType("numeric(19,4)")
                                .HasColumnName("inventory_value_amount");

                            b1.Property<string>("CurrencyCode")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("character(3)")
                                .HasColumnName("inventory_value_currency_code")
                                .IsFixedLength();

                            b1.HasKey("InventoryBalanceId");

                            b1.ToTable("inventory_balances", "erp");

                            b1.WithOwner()
                                .HasForeignKey("InventoryBalanceId");
                        });

                    b.OwnsOne("Erp.Domain.Common.Quantity", "OnHandQuantity", b1 =>
                        {
                            b1.Property<Guid>("InventoryBalanceId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("Amount")
                                .HasPrecision(19, 6)
                                .HasColumnType("numeric(19,6)")
                                .HasColumnName("on_hand_quantity_amount");

                            b1.Property<Guid>("UnitOfMeasureId")
                                .HasColumnType("uuid")
                                .HasColumnName("on_hand_quantity_unit_of_measure_id");

                            b1.HasKey("InventoryBalanceId");

                            b1.HasIndex("UnitOfMeasureId");

                            b1.ToTable("inventory_balances", "erp");

                            b1.WithOwner()
                                .HasForeignKey("InventoryBalanceId");

                            b1.HasOne("Erp.Domain.MasterData.UnitOfMeasure", null)
                                .WithMany()
                                .HasForeignKey("UnitOfMeasureId")
                                .OnDelete(DeleteBehavior.Restrict)
                                .IsRequired();
                        });

                    b.Navigation("InventoryValue")
                        .IsRequired();

                    b.Navigation("OnHandQuantity")
                        .IsRequired();
                });

            modelBuilder.Entity("Erp.Domain.Inventory.InventoryTransaction", b =>
                {
                    b.HasOne("Erp.Domain.Organizations.Company", null)
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Erp.Domain.MasterData.Product", null)
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Erp.Domain.Inventory.Warehouse", null)
                        .WithMany()
                        .HasForeignKey("WarehouseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsOne("Erp.Domain.Common.Money", "CostAmount", b1 =>
                        {
                            b1.Property<Guid>("InventoryTransactionId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("Amount")
                                .HasPrecision(19, 4)
                                .HasColumnType("numeric(19,4)")
                                .HasColumnName("cost_amount");

                            b1.Property<string>("CurrencyCode")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("character(3)")
                                .HasColumnName("cost_currency_code")
                                .IsFixedLength();

                            b1.HasKey("InventoryTransactionId");

                            b1.ToTable("inventory_transactions", "erp");

                            b1.WithOwner()
                                .HasForeignKey("InventoryTransactionId");
                        });

                    b.OwnsOne("Erp.Domain.Common.Quantity", "Quantity", b1 =>
                        {
                            b1.Property<Guid>("InventoryTransactionId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("Amount")
                                .HasPrecision(19, 6)
                                .HasColumnType("numeric(19,6)")
                                .HasColumnName("quantity_amount");

                            b1.Property<Guid>("UnitOfMeasureId")
                                .HasColumnType("uuid")
                                .HasColumnName("quantity_unit_of_measure_id");

                            b1.HasKey("InventoryTransactionId");

                            b1.HasIndex("UnitOfMeasureId");

                            b1.ToTable("inventory_transactions", "erp");

                            b1.WithOwner()
                                .HasForeignKey("InventoryTransactionId");

                            b1.HasOne("Erp.Domain.MasterData.UnitOfMeasure", null)
                                .WithMany()
                                .HasForeignKey("UnitOfMeasureId")
                                .OnDelete(DeleteBehavior.Restrict)
                                .IsRequired();
                        });

                    b.OwnsOne("Erp.Domain.Common.SourceReference", "SourceReference", b1 =>
                        {
                            b1.Property<Guid>("InventoryTransactionId")
                                .HasColumnType("uuid");

                            b1.Property<Guid>("AggregateId")
                                .HasColumnType("uuid")
                                .HasColumnName("source_aggregate_id");

                            b1.Property<string>("EventType")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("source_event_type");

                            b1.Property<string>("Module")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("source_module");

                            b1.HasKey("InventoryTransactionId");

                            b1.HasIndex("Module", "AggregateId", "EventType");

                            b1.ToTable("inventory_transactions", "erp");

                            b1.WithOwner()
                                .HasForeignKey("InventoryTransactionId");
                        });

                    b.Navigation("CostAmount");

                    b.Navigation("Quantity")
                        .IsRequired();

                    b.Navigation("SourceReference")
                        .IsRequired();
                });

            modelBuilder.Entity("Erp.Domain.Inventory.Warehouse", b =>
                {
                    b.HasOne("Erp.Domain.Organizations.Company", null)
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Erp.Domain.MasterData.BusinessPartner", b =>
                {
                    b.HasOne("Erp.Domain.Organizations.Company", null)
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsOne("Erp.Domain.Common.Address", "Address", b1 =>
                        {
                            b1.Property<Guid>("BusinessPartnerId")
                                .HasColumnType("uuid");

                            b1.Property<string>("City")
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("address_city");

                            b1.Property<string>("CountryCode")
                                .IsRequired()
                                .HasMaxLength(2)
                                .HasColumnType("character(2)")
                                .HasColumnName("address_country_code")
                                .IsFixedLength();

                            b1.Property<string>("Line1")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("address_line_1");

                            b1.Property<string>("Line2")
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("address_line_2");

                            b1.Property<string>("PostalCode")
                                .HasMaxLength(30)
                                .HasColumnType("character varying(30)")
                                .HasColumnName("address_postal_code");

                            b1.HasKey("BusinessPartnerId");

                            b1.ToTable("business_partners", "erp");

                            b1.WithOwner()
                                .HasForeignKey("BusinessPartnerId");
                        });

                    b.OwnsOne("Erp.Domain.Common.ContactDetails", "ContactDetails", b1 =>
                        {
                            b1.Property<Guid>("BusinessPartnerId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Email")
                                .HasMaxLength(254)
                                .HasColumnType("character varying(254)")
                                .HasColumnName("contact_email");

                            b1.Property<string>("Phone")
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("contact_phone");

                            b1.HasKey("BusinessPartnerId");

                            b1.ToTable("business_partners", "erp");

                            b1.WithOwner()
                                .HasForeignKey("BusinessPartnerId");
                        });

                    b.Navigation("Address")
                        .IsRequired();

                    b.Navigation("ContactDetails")
                        .IsRequired();
                });

            modelBuilder.Entity("Erp.Domain.MasterData.CustomerProfile", b =>
                {
                    b.HasOne("Erp.Domain.MasterData.BusinessPartner", null)
                        .WithOne("CustomerProfile")
                        .HasForeignKey("Erp.Domain.MasterData.CustomerProfile", "BusinessPartnerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Erp.Domain.Accounting.Account", null)
                        .WithMany()
                        .HasForeignKey("ReceivableAccountId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.OwnsOne("Erp.Domain.Common.Money", "CreditLimit", b1 =>
                        {
                            b1.Property<Guid>("CustomerProfileId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("Amount")
                                .HasPrecision(19, 4)
                                .HasColumnType("numeric(19,4)")
                                .HasColumnName("credit_limit_amount");

                            b1.Property<string>("CurrencyCode")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("character(3)")
                                .HasColumnName("credit_limit_currency_code")
                                .IsFixedLength();

                            b1.HasKey("CustomerProfileId");

                            b1.ToTable("customer_profiles", "erp");

                            b1.WithOwner()
                                .HasForeignKey("CustomerProfileId");
                        });

                    b.Navigation("CreditLimit");
                });

            modelBuilder.Entity("Erp.Domain.MasterData.Product", b =>
                {
                    b.HasOne("Erp.Domain.Organizations.Company", null)
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Erp.Domain.Accounting.PostingProfile", null)
                        .WithMany()
                        .HasForeignKey("PostingProfileId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Erp.Domain.MasterData.ProductCategory", null)
                        .WithMany()
                        .HasForeignKey("ProductCategoryId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Erp.Domain.MasterData.UnitOfMeasure", null)
                        .WithMany()
                        .HasForeignKey("StockUnitOfMeasureId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Erp.Domain.MasterData.ProductCategory", b =>
                {
                    b.HasOne("Erp.Domain.Organizations.Company", null)
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Erp.Domain.MasterData.ProductCategory", null)
                        .WithMany()
                        .HasForeignKey("ParentCategoryId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Erp.Domain.MasterData.SupplierProfile", b =>
                {
                    b.HasOne("Erp.Domain.MasterData.BusinessPartner", null)
                        .WithOne("SupplierProfile")
                        .HasForeignKey("Erp.Domain.MasterData.SupplierProfile", "BusinessPartnerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Erp.Domain.Accounting.Account", null)
                        .WithMany()
                        .HasForeignKey("PayableAccountId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Erp.Domain.MasterData.TaxCode", b =>
                {
                    b.HasOne("Erp.Domain.Organizations.Company", null)
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Erp.Domain.MasterData.UnitOfMeasure", b =>
                {
                    b.HasOne("Erp.Domain.Organizations.Company", null)
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Erp.Domain.Organizations.Company", b =>
                {
                    b.HasOne("Erp.Domain.Organizations.Organization", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Erp.Domain.Payments.Payment", b =>
                {
                    b.HasOne("Erp.Domain.MasterData.BusinessPartner", null)
                        .WithMany()
                        .HasForeignKey("BusinessPartnerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Erp.Domain.Accounting.CashBankAccount", null)
                        .WithMany()
                        .HasForeignKey("CashBankAccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Erp.Domain.Organizations.Company", null)
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsOne("Erp.Domain.Common.Money", "Amount", b1 =>
                        {
                            b1.Property<Guid>("PaymentId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("Amount")
                                .HasPrecision(19, 4)
                                .HasColumnType("numeric(19,4)")
                                .HasColumnName("payment_amount");

                            b1.Property<string>("CurrencyCode")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("character(3)")
                                .HasColumnName("payment_currency_code")
                                .IsFixedLength();

                            b1.HasKey("PaymentId");

                            b1.ToTable("payments", "erp");

                            b1.WithOwner()
                                .HasForeignKey("PaymentId");
                        });

                    b.Navigation("Amount")
                        .IsRequired();
                });

            modelBuilder.Entity("Erp.Domain.Payments.PaymentAllocation", b =>
                {
                    b.HasOne("Erp.Domain.Accounting.OpenItem", null)
                        .WithMany()
                        .HasForeignKey("OpenItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Erp.Domain.Payments.Payment", null)
                        .WithMany("Allocations")
                        .HasForeignKey("PaymentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsOne("Erp.Domain.Common.Money", "Amount", b1 =>
                        {
                            b1.Property<Guid>("PaymentAllocationId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("Amount")
                                .HasPrecision(19, 4)
                                .HasColumnType("numeric(19,4)")
                                .HasColumnName("allocated_amount");

                            b1.Property<string>("CurrencyCode")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("character(3)")
                                .HasColumnName("allocated_currency_code")
                                .IsFixedLength();

                            b1.HasKey("PaymentAllocationId");

                            b1.ToTable("payment_allocations", "erp");

                            b1.WithOwner()
                                .HasForeignKey("PaymentAllocationId");
                        });

                    b.Navigation("Amount")
                        .IsRequired();
                });

            modelBuilder.Entity("Erp.Domain.Purchasing.PurchaseInvoice", b =>
                {
                    b.HasOne("Erp.Domain.Organizations.Company", null)
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Erp.Domain.MasterData.BusinessPartner", null)
                        .WithMany()
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsOne("Erp.Domain.Common.SourceReference", "SourceReference", b1 =>
                        {
                            b1.Property<Guid>("PurchaseInvoiceId")
                                .HasColumnType("uuid");

                            b1.Property<Guid>("AggregateId")
                                .HasColumnType("uuid")
                                .HasColumnName("source_aggregate_id");

                            b1.Property<string>("EventType")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("source_event_type");

                            b1.Property<string>("Module")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("source_module");

                            b1.HasKey("PurchaseInvoiceId");

                            b1.HasIndex("Module", "AggregateId", "EventType");

                            b1.ToTable("purchase_invoices", "erp");

                            b1.WithOwner()
                                .HasForeignKey("PurchaseInvoiceId");
                        });

                    b.Navigation("SourceReference");
                });

            modelBuilder.Entity("Erp.Domain.Purchasing.PurchaseInvoiceLine", b =>
                {
                    b.HasOne("Erp.Domain.Accounting.PostingProfile", null)
                        .WithMany()
                        .HasForeignKey("PostingProfileId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Erp.Domain.MasterData.Product", null)
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Erp.Domain.Purchasing.PurchaseInvoice", null)
                        .WithMany("Lines")
                        .HasForeignKey("PurchaseInvoiceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsOne("Erp.Domain.Common.Quantity", "Quantity", b1 =>
                        {
                            b1.Property<Guid>("PurchaseInvoiceLineId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("Amount")
                                .HasPrecision(19, 6)
                                .HasColumnType("numeric(19,6)")
                                .HasColumnName("quantity_amount");

                            b1.Property<Guid>("UnitOfMeasureId")
                                .HasColumnType("uuid")
                                .HasColumnName("quantity_unit_of_measure_id");

                            b1.HasKey("PurchaseInvoiceLineId");

                            b1.HasIndex("UnitOfMeasureId");

                            b1.ToTable("purchase_invoice_lines", "erp");

                            b1.WithOwner()
                                .HasForeignKey("PurchaseInvoiceLineId");

                            b1.HasOne("Erp.Domain.MasterData.UnitOfMeasure", null)
                                .WithMany()
                                .HasForeignKey("UnitOfMeasureId")
                                .OnDelete(DeleteBehavior.Restrict)
                                .IsRequired();
                        });

                    b.OwnsOne("Erp.Domain.Common.TaxSnapshot", "Tax", b1 =>
                        {
                            b1.Property<Guid>("PurchaseInvoiceLineId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("Rate")
                                .HasPrecision(5, 2)
                                .HasColumnType("numeric(5,2)")
                                .HasColumnName("tax_rate");

                            b1.Property<Guid>("TaxCodeId")
                                .HasColumnType("uuid")
                                .HasColumnName("tax_tax_code_id");

                            b1.HasKey("PurchaseInvoiceLineId");

                            b1.HasIndex("TaxCodeId");

                            b1.ToTable("purchase_invoice_lines", "erp");

                            b1.WithOwner()
                                .HasForeignKey("PurchaseInvoiceLineId");

                            b1.HasOne("Erp.Domain.MasterData.TaxCode", null)
                                .WithMany()
                                .HasForeignKey("TaxCodeId")
                                .OnDelete(DeleteBehavior.Restrict)
                                .IsRequired();
                        });

                    b.OwnsOne("Erp.Domain.Common.Money", "UnitCost", b1 =>
                        {
                            b1.Property<Guid>("PurchaseInvoiceLineId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("Amount")
                                .HasPrecision(19, 4)
                                .HasColumnType("numeric(19,4)")
                                .HasColumnName("unit_cost_amount");

                            b1.Property<string>("CurrencyCode")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("character(3)")
                                .HasColumnName("unit_cost_currency_code")
                                .IsFixedLength();

                            b1.HasKey("PurchaseInvoiceLineId");

                            b1.ToTable("purchase_invoice_lines", "erp");

                            b1.WithOwner()
                                .HasForeignKey("PurchaseInvoiceLineId");
                        });

                    b.Navigation("Quantity")
                        .IsRequired();

                    b.Navigation("Tax")
                        .IsRequired();

                    b.Navigation("UnitCost")
                        .IsRequired();
                });

            modelBuilder.Entity("Erp.Domain.Sales.SalesInvoice", b =>
                {
                    b.HasOne("Erp.Domain.Organizations.Company", null)
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Erp.Domain.MasterData.BusinessPartner", null)
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsOne("Erp.Domain.Common.SourceReference", "SourceReference", b1 =>
                        {
                            b1.Property<Guid>("SalesInvoiceId")
                                .HasColumnType("uuid");

                            b1.Property<Guid>("AggregateId")
                                .HasColumnType("uuid")
                                .HasColumnName("source_aggregate_id");

                            b1.Property<string>("EventType")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("source_event_type");

                            b1.Property<string>("Module")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("source_module");

                            b1.HasKey("SalesInvoiceId");

                            b1.HasIndex("Module", "AggregateId", "EventType");

                            b1.ToTable("sales_invoices", "erp");

                            b1.WithOwner()
                                .HasForeignKey("SalesInvoiceId");
                        });

                    b.Navigation("SourceReference");
                });

            modelBuilder.Entity("Erp.Domain.Sales.SalesInvoiceLine", b =>
                {
                    b.HasOne("Erp.Domain.MasterData.Product", null)
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Erp.Domain.Sales.SalesInvoice", null)
                        .WithMany("Lines")
                        .HasForeignKey("SalesInvoiceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsOne("Erp.Domain.Common.Quantity", "Quantity", b1 =>
                        {
                            b1.Property<Guid>("SalesInvoiceLineId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("Amount")
                                .HasPrecision(19, 6)
                                .HasColumnType("numeric(19,6)")
                                .HasColumnName("quantity_amount");

                            b1.Property<Guid>("UnitOfMeasureId")
                                .HasColumnType("uuid")
                                .HasColumnName("quantity_unit_of_measure_id");

                            b1.HasKey("SalesInvoiceLineId");

                            b1.HasIndex("UnitOfMeasureId");

                            b1.ToTable("sales_invoice_lines", "erp");

                            b1.WithOwner()
                                .HasForeignKey("SalesInvoiceLineId");

                            b1.HasOne("Erp.Domain.MasterData.UnitOfMeasure", null)
                                .WithMany()
                                .HasForeignKey("UnitOfMeasureId")
                                .OnDelete(DeleteBehavior.Restrict)
                                .IsRequired();
                        });

                    b.OwnsOne("Erp.Domain.Common.TaxSnapshot", "Tax", b1 =>
                        {
                            b1.Property<Guid>("SalesInvoiceLineId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("Rate")
                                .HasPrecision(5, 2)
                                .HasColumnType("numeric(5,2)")
                                .HasColumnName("tax_rate");

                            b1.Property<Guid>("TaxCodeId")
                                .HasColumnType("uuid")
                                .HasColumnName("tax_tax_code_id");

                            b1.HasKey("SalesInvoiceLineId");

                            b1.HasIndex("TaxCodeId");

                            b1.ToTable("sales_invoice_lines", "erp");

                            b1.WithOwner()
                                .HasForeignKey("SalesInvoiceLineId");

                            b1.HasOne("Erp.Domain.MasterData.TaxCode", null)
                                .WithMany()
                                .HasForeignKey("TaxCodeId")
                                .OnDelete(DeleteBehavior.Restrict)
                                .IsRequired();
                        });

                    b.OwnsOne("Erp.Domain.Common.Money", "UnitPrice", b1 =>
                        {
                            b1.Property<Guid>("SalesInvoiceLineId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("Amount")
                                .HasPrecision(19, 4)
                                .HasColumnType("numeric(19,4)")
                                .HasColumnName("unit_price_amount");

                            b1.Property<string>("CurrencyCode")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("character(3)")
                                .HasColumnName("unit_price_currency_code")
                                .IsFixedLength();

                            b1.HasKey("SalesInvoiceLineId");

                            b1.ToTable("sales_invoice_lines", "erp");

                            b1.WithOwner()
                                .HasForeignKey("SalesInvoiceLineId");
                        });

                    b.Navigation("Quantity")
                        .IsRequired();

                    b.Navigation("Tax")
                        .IsRequired();

                    b.Navigation("UnitPrice")
                        .IsRequired();
                });

            modelBuilder.Entity("Erp.Infrastructure.Authentication.UserCredential", b =>
                {
                    b.HasOne("Erp.Domain.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Erp.Domain.Accounting.ChartOfAccounts", b =>
                {
                    b.Navigation("Accounts");
                });

            modelBuilder.Entity("Erp.Domain.Accounting.JournalEntry", b =>
                {
                    b.Navigation("Lines");
                });

            modelBuilder.Entity("Erp.Domain.Accounting.PostingProfile", b =>
                {
                    b.Navigation("Entries");
                });

            modelBuilder.Entity("Erp.Domain.Identity.Role", b =>
                {
                    b.Navigation("Permissions");
                });

            modelBuilder.Entity("Erp.Domain.Identity.User", b =>
                {
                    b.Navigation("RoleAssignments");
                });

            modelBuilder.Entity("Erp.Domain.MasterData.BusinessPartner", b =>
                {
                    b.Navigation("CustomerProfile");

                    b.Navigation("SupplierProfile");
                });

            modelBuilder.Entity("Erp.Domain.Payments.Payment", b =>
                {
                    b.Navigation("Allocations");
                });

            modelBuilder.Entity("Erp.Domain.Purchasing.PurchaseInvoice", b =>
                {
                    b.Navigation("Lines");
                });

            modelBuilder.Entity("Erp.Domain.Sales.SalesInvoice", b =>
                {
                    b.Navigation("Lines");
                });
#pragma warning restore 612, 618
        }
    }
}
