import { formatAmount, utcDateInput } from '../../shared/utils/display-format';
import { CommonModule } from '@angular/common';
import { Component, OnInit } from '@angular/core';
import { FormArray, FormBuilder, FormsModule, ReactiveFormsModule, Validators } from '@angular/forms';
import { ActivatedRoute, Router, RouterLink } from '@angular/router';

import { AuthService } from '../../core/auth/auth.service';
import { InventoryService } from '../inventory/inventory.service';
import { Warehouse } from '../inventory/inventory.models';
import { Partner, Product } from '../master-data/master-data.models';
import { MasterDataService } from '../master-data/master-data.service';
import { PurchaseBill, PurchaseBillInput, PurchaseBillStatus } from './purchase.models';
import { PurchaseService } from './purchase.service';

@Component({
  selector: 'app-purchase-bill-list',
  standalone: true,
  imports: [CommonModule, FormsModule, ReactiveFormsModule, RouterLink],
  styleUrl: '../sales/sales-invoice-list.component.scss',
  template: `
    <section class="sales-page">
      <header class="page-heading"><div><span class="eyebrow">Purchasing</span><h1>Purchase bills</h1><p>Draft bills are safe to edit. Posting receives stock and creates an accounts payable item.</p></div><button *ngIf="canManage" type="button" class="primary-action" (click)="openCreate()">New purchase bill</button></header>
      <div class="notice error" *ngIf="errorMessage">{{ errorMessage }}</div><div class="notice success" *ngIf="successMessage">{{ successMessage }}</div>
      <section class="filters"><input [(ngModel)]="search" placeholder="Search bill, supplier, or supplier reference" (keyup.enter)="applyFilters()"><select [(ngModel)]="supplierFilter"><option value="">All suppliers</option><option *ngFor="let supplier of suppliers" [value]="supplier.id">{{ supplier.code }} — {{ supplier.legalName }}</option></select><select [(ngModel)]="statusFilter"><option value="">All statuses</option><option value="Draft">Draft</option><option value="Posted">Posted</option></select><input type="date" [(ngModel)]="fromDate"><input type="date" [(ngModel)]="toDate"><button type="button" (click)="applyFilters()">Apply</button><button type="button" class="quiet" (click)="clearFilters()">Clear</button></section>
      <section class="editor" *ngIf="isFormOpen"><header><div><h2>{{ editingBill ? 'Edit draft purchase bill' : 'New purchase bill' }}</h2><p>Only posting changes inventory and accounts payable.</p></div><button type="button" class="quiet" (click)="closeForm()">Close</button></header><div class="notice error" *ngIf="formError">{{ formError }}</div><form [formGroup]="form" (ngSubmit)="saveDraft()"><div class="form-grid"><label>Supplier<select formControlName="supplierId"><option value="">Select supplier</option><option *ngFor="let supplier of suppliers" [value]="supplier.id">{{ supplier.code }} — {{ supplier.legalName }}</option></select></label><label>Warehouse<select formControlName="warehouseId"><option value="">No warehouse (service-only bill)</option><option *ngFor="let warehouse of warehouses" [value]="warehouse.id">{{ warehouse.code }} — {{ warehouse.name }}</option></select></label><label>Bill date<input type="date" formControlName="invoiceDate"></label><label>Due date<input type="date" formControlName="dueDate"></label><label>Supplier invoice reference<input formControlName="supplierReference" maxlength="100"></label><label>Notes<textarea formControlName="notes" maxlength="1000"></textarea></label></div><div class="lines" formArrayName="lines"><div class="line-header"><strong>Product</strong><strong>Description</strong><strong>Quantity</strong><strong>Unit cost</strong><strong>Discount</strong><strong>Total</strong><span></span></div><div class="line-row" *ngFor="let line of lines.controls; let index = index" [formGroupName]="index"><select formControlName="productId" (change)="onProductSelected(index)"><option value="">Select product</option><option *ngFor="let product of products" [value]="product.id">{{ product.sku }} — {{ product.name }}</option></select><input formControlName="description"><input type="number" min="0.0001" step="any" formControlName="quantity"><input type="number" min="0" step="any" formControlName="unitCost"><input type="number" min="0" max="100" step="any" formControlName="discountPercentage"><span>{{ previewLineTotal(index) | number:'1.2-2' }}</span><button type="button" class="quiet" (click)="removeLine(index)" [disabled]="lines.length === 1">Remove</button></div></div><button type="button" class="quiet" (click)="addLine()">Add line</button><footer><strong>Draft total: {{ draftTotalPreview | number:'1.2-2' }}</strong><button type="submit" class="primary-action" [disabled]="isSaving">{{ isSaving ? 'Saving…' : 'Save draft' }}</button></footer></form></section>
      <section class="table-card"><div class="loading" *ngIf="isLoading">Loading purchase bills…</div><table *ngIf="!isLoading"><thead><tr><th>Bill</th><th>Supplier</th><th>Bill / due date</th><th>Status</th><th>Total</th><th>Outstanding</th></tr></thead><tbody><tr *ngFor="let bill of bills"><td><a [routerLink]="['/purchases', bill.id]">{{ bill.purchaseBillNumber }}</a><small *ngIf="bill.supplierReference">{{ bill.supplierReference }}</small></td><td>{{ bill.supplierName }}<small>{{ bill.supplierCode }}</small></td><td>{{ bill.invoiceDate | date }}<small>{{ bill.dueDate ? (bill.dueDate | date) : 'No due date' }}</small></td><td><span class="status" [class.posted]="bill.status === 'Posted'">{{ bill.status }}{{ bill.paymentStatus ? ' · ' + bill.paymentStatus : '' }}</span></td><td>{{ formatAmount(bill.total, bill.currencyCode) }}</td><td>{{ bill.status === 'Posted' ? formatAmount(bill.outstandingAmount, bill.currencyCode) : '—' }}</td></tr><tr *ngIf="bills.length === 0"><td colspan="6" class="empty">No purchase bills match these filters.</td></tr></tbody></table></section>
    </section>`
})
export class PurchaseBillListComponent implements OnInit {
  private readonly formBuilder = new FormBuilder().nonNullable;
  readonly form = this.formBuilder.group({ supplierId: ['', Validators.required], warehouseId: [''], invoiceDate: [this.today(), Validators.required], dueDate: [''], supplierReference: ['', Validators.maxLength(100)], notes: ['', Validators.maxLength(1000)], lines: this.formBuilder.array([this.createLine()]) });
  bills: PurchaseBill[] = []; suppliers: Partner[] = []; products: Product[] = []; warehouses: Warehouse[] = [];
  search = ''; supplierFilter = ''; statusFilter: PurchaseBillStatus | '' = ''; fromDate = ''; toDate = ''; isLoading = true; isSaving = false; isFormOpen = false; errorMessage = ''; formError = ''; successMessage = ''; editingBill?: PurchaseBill;
  constructor(private readonly purchases: PurchaseService, private readonly masterData: MasterDataService, private readonly inventory: InventoryService, private readonly route: ActivatedRoute, private readonly router: Router, readonly auth: AuthService) {}
  ngOnInit(): void { this.load(); this.masterData.list<Partner>('suppliers', { isActive: true, pageNumber: 1, pageSize: 100 }).subscribe({ next: result => this.suppliers = result.items }); this.masterData.list<Product>('products', { isActive: true, pageNumber: 1, pageSize: 100 }).subscribe({ next: result => this.products = result.items }); this.inventory.listWarehouses({ isActive: true, pageNumber: 1, pageSize: 100 }).subscribe({ next: result => this.warehouses = result.items }); const id = this.route.snapshot.queryParamMap.get('edit'); if (id && this.canManage) this.loadDraft(id); }
  get lines(): FormArray { return this.form.controls.lines; }
  get canManage(): boolean { return this.auth.currentUser?.permissions.includes('purchases.manage') === true; }
  get draftTotalPreview(): number { return this.lines.controls.reduce((total, control) => total + this.lineTotal(control.getRawValue() as { quantity: number; unitCost: number; discountPercentage: number }), 0); }
  load(): void { this.isLoading = true; this.purchases.listBills({ search: this.search, supplierId: this.supplierFilter, status: this.statusFilter, fromDate: this.fromDate, toDate: this.toDate, pageNumber: 1, pageSize: 100 }).subscribe({ next: page => { this.bills = page.items; this.isLoading = false; }, error: () => { this.errorMessage = 'We could not load purchase bills.'; this.isLoading = false; } }); }
  applyFilters(): void { this.load(); }
  clearFilters(): void { this.search = ''; this.supplierFilter = ''; this.statusFilter = ''; this.fromDate = ''; this.toDate = ''; this.load(); }
  openCreate(): void { this.editingBill = undefined; this.form.reset({ supplierId: '', warehouseId: '', invoiceDate: this.today(), dueDate: '', supplierReference: '', notes: '' }); while (this.lines.length > 1) this.lines.removeAt(this.lines.length - 1); this.lines.at(0).reset({ productId: '', description: '', quantity: 1, unitCost: 0, discountPercentage: 0, memo: '' }); this.isFormOpen = true; this.formError = ''; }
  closeForm(): void { this.isFormOpen = false; this.editingBill = undefined; void this.router.navigate([], { relativeTo: this.route, queryParams: { edit: null }, queryParamsHandling: 'merge', replaceUrl: true }); }
  addLine(): void { this.lines.push(this.createLine()); }
  removeLine(index: number): void { if (this.lines.length > 1) this.lines.removeAt(index); }
  onProductSelected(index: number): void { const product = this.products.find(candidate => candidate.id === this.lines.at(index).get('productId')?.value); if (product) this.lines.at(index).patchValue({ description: product.name }); }
  previewLineTotal(index: number): number { return this.lineTotal(this.lines.at(index).getRawValue() as { quantity: number; unitCost: number; discountPercentage: number }); }
  saveDraft(): void { if (!this.canManage || this.form.invalid || this.isSaving) { this.form.markAllAsTouched(); return; } const value = this.form.getRawValue(); const input: PurchaseBillInput = { supplierId: value.supplierId, warehouseId: value.warehouseId || null, invoiceDate: value.invoiceDate, dueDate: value.dueDate || null, supplierReference: value.supplierReference || null, notes: value.notes || null, lines: value.lines.map(line => ({ productId: line.productId, description: line.description || null, quantity: Number(line.quantity), unitCost: Number(line.unitCost), discountPercentage: Number(line.discountPercentage), memo: line.memo || null })) }; this.isSaving = true; const request = this.editingBill ? this.purchases.updateBill(this.editingBill.id, input) : this.purchases.createBill(input); request.subscribe({ next: bill => void this.router.navigate(['/purchases', bill.id]), error: error => { this.formError = error.error?.title || 'We could not save this purchase bill draft.'; this.isSaving = false; } }); }
  formatAmount(amount: number, currency: string): string { return `${currency} ${formatAmount(amount)}`; }
  private loadDraft(id: string): void { this.purchases.getBill(id).subscribe({ next: bill => { if (bill.status !== 'Draft') return; this.editingBill = bill; this.form.patchValue({ supplierId: bill.supplierId, warehouseId: bill.warehouseId || '', invoiceDate: bill.invoiceDate, dueDate: bill.dueDate || '', supplierReference: bill.supplierReference || '', notes: bill.notes || '' }); this.lines.clear(); bill.lines.forEach(line => this.lines.push(this.createLine(line))); this.isFormOpen = true; }, error: () => this.errorMessage = 'We could not open that purchase bill draft.' }); }
  private createLine(line?: Partial<PurchaseBill['lines'][number]>) { return this.formBuilder.group({ productId: [line?.productId || '', Validators.required], description: [line?.description || ''], quantity: [line?.quantity || 1, [Validators.required, Validators.min(0.000001)]], unitCost: [line?.unitCost || 0, [Validators.required, Validators.min(0)]], discountPercentage: [line?.discountPercentage || 0, [Validators.min(0), Validators.max(100)]], memo: [line?.memo || ''] }); }
  private lineTotal(line: { quantity: number; unitCost: number; discountPercentage: number }): number { return Number(line.quantity || 0) * Number(line.unitCost || 0) * (1 - Number(line.discountPercentage || 0) / 100); }
  private today(): string { return utcDateInput(); }
}
